# Site settings
title: painer.de
email: sven@painer.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.painer.de" # the base hostname & protocol for your site
host: rasppi

# Build settings
markdown: kramdown
exclude: [gulpfile.js, package.json, node_modules, LICENSE, README.md, assets/scripts]
keep_files: [assets/scripts_head.js, assets/scripts_main.js]

sass:
  style: expanded

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      lang: en
  -
    scope:
      path: de
    values:
      lang: de
  -
    scope:
      path: en
    values:
      lang: en
